# Generated by Django 4.2.3 on 2023-09-01 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('ScName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ScPrincipal', models.CharField(max_length=100)),
                ('ScLocation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SName', models.CharField(max_length=100)),
                ('Sid', models.IntegerField()),
                ('ScName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.school')),
            ],
        ),
    ]
