# Generated by Django 4.2.3 on 2023-09-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='Sid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
